apiVersion: v1
kind: PersistentVolume
metadata:
  name: anobbs-mongo-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nas.thoxvi.com
    path: /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anobbs-mongo-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi
