apiVersion: v1
kind: PersistentVolume
metadata:
  name: anobbs-mongo-pv
  labels:
    pv-type: mongo
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nas.thoxvi.com
    path: /data/anobbs_mongo
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: anobbs-redis-pv
  labels:
    pv-type: redis
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nas.thoxvi.com
    path: /data/anobbs_redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anobbs-mongo-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      pv-type: mongo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anobbs-redis-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      pv-type: redis
